### ISSUE TITLE
console version?

### ISSUE THREAD

**Issue by MrTomiCZ** [Tsimbalist/DiscordSC#1]
Hey, i would like if you could provide a console version, i wanna run it on a rpi3a+ and leave it on overnight.

**Comment by Tsimbalist** [comment]
Hey! Thanks for your interest in a console version of DiscordSC. To have the custom status working, you'll need to keep Discord running on the same device where the program is executed. So, if you run the console version on your Raspberry Pi, make sure that Discord is open on that device for it to update the status.

If you need a console version, I'm ready to create one for you. If you have any questions or need further help, feel free to ask!

**Comment by MrTomiCZ** [comment]
Oh okay, so that wont probably work because of 512mb RAM (chromium barely launches) so i would want something without the DC client in the background. Very nice app i forgot to say

**Comment by MrTomiCZ** [comment]
Oooooh, I completely forgot how status changers work (rpc) i see why it needs to be in background

**Comment by Tsimbalist** [comment]
Glad you remembered how it works! Unfortunately, without the Discord client running, it won’t be possible. Thanks for the kind words! If you like the app, feel free to leave a star on GitHub 😊

**Comment by MrTomiCZ** [comment]
Yes, I sure will leave a star. Thanks for the response!

**Comment by Tsimbalist** [comment]
You're welcome! Thanks a lot for the support! 😊
